### ISSUE TITLE
java.lang.RuntimeException: Class java/util/UUID could not be instrumented

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/flacoco#106]
On Oracle JDK 11, Astor fails with `Class java/util/UUID could not be instrumented`.

Reference: https://ci.inria.fr/sos/job/astor/1067/

Is there a way to exclude java.* from being instrumented?

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
	at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
	at org.jacoco.agent.rt.internal_b0d6a23.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_b0d6a23.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
FATAL ERROR in native method: processing of -javaagent failed
	at java.base/java.lang.Class.getField(Class.java:2000)
	at org.jacoco.agent.rt.internal_b0d6a23.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
	... 9 more
```

**Comment by monperrus** [comment]
> if you think we should have it as default for flacoco that's possible too

sounds like a good safe default to me, WDYT?

**Comment by monperrus** [comment]
The problem is still there, see https://ci.inria.fr/sos/job/astor/1068/display/redirect?page=changes

Is the exclude well propagated?

**Comment by andre15silva** [comment]
Hi @monperrus,

My bad, I didn't read the entire log. It seems to me that the issue isn't in flacoco actually, but with the jacoco agent that runs on astor (for code coverage only). If it where to be in flacoco then we would see that some test had begun, which is not the case.

I would suggest the following:
- Upgrade the version to `0.8.7` here: https://github.com/SpoonLabs/astor/blob/9f0249228db76b8f94d0ed7947b7d2e53f9e5c07/pom.xml#L264-L267 
- If that doesn't work, include `java.*` in the jacoco exclude patterns in the `pom.xml`

**Comment by monperrus** [comment]
> Upgrade the version to 0.8.7 here: SpoonLabs/astor@9f02492/pom.xml#L264-L267 

What about PRing on Astor also?

**Comment by andre15silva** [comment]
> > Upgrade the version to 0.8.7 here: [SpoonLabs/astor@9f02492](https://github.com/SpoonLabs/astor/commit/9f02492)/pom.xml#L264-L267
> 
> What about PRing on Astor also?

WDYM? That PR was on Astor, and has already been merged by Matias today.

**Comment by monperrus** [comment]
my bad.

this problem seems solved, now we're running into another one, see https://github.com/SpoonLabs/astor/issues/338
