### ISSUE TITLE
Unrepaired Chart-15 by Flacoco

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/flacoco#108]
The suspicious line where Astor finds a fix 
(https://github.com/martinezmatias/astor/runs/3851808653?check_suite_focus=true#step:8:1938) is not included by Flacoco in the suspicious list

**Comment by andre15silva** [comment]
This is the same of #109

In this case, this exception is thrown:
```
java.lang.IllegalArgumentException: Null 'dataset' argument.
	at org.jfree.data.general.DatasetUtilities.calculatePieDatasetTotal(DatasetUtilities.java:153)
	at org.jfree.chart.plot.PiePlot.initialise(PiePlot.java:2051)
	at org.jfree.chart.plot.PiePlot3D.draw(PiePlot3D.java:280)
	at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1219)
	at org.jfree.chart.plot.junit.PiePlot3DTests.testDrawWithNullDataset(PiePlot3DTests.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
```

It is not as obvious because the test case that fails catches it and then fails afterwards:
```java
    public void testDrawWithNullDataset() {
        JFreeChart chart = ChartFactory.createPieChart3D("Test", null, true, 
                false, false);
        boolean success = false;
        try {
            BufferedImage image = new BufferedImage(200 , 100, 
                    BufferedImage.TYPE_INT_RGB);
            Graphics2D g2 = image.createGraphics();
            chart.draw(g2, new Rectangle2D.Double(0, 0, 200, 100), null, null);
            g2.dispose();
            success = true;
        }
        catch (Exception e) {
            success = false;
        }
        assertTrue(success);
    }
```

**Comment by monperrus** [comment]
As suggest bu @andre15silva we can slightly refactor the test

**Comment by martinezmatias** [comment]
Using a refactored version of the buggy project, we repair the bug as the suspicious line appears in the suspicious list: https://github.com/martinezmatias/astor/runs/4168386737?check_suite_focus=true#step:8:11547
